"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
// import StoreProvider from './StoreProvider'
import { useContext, createContext, useState, SetStateAction, Dispatch } from 'react'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'My page',
  description: 'Generated by create next app',
}
export const ThemeContext = createContext<{ theme: string; setTheme: Dispatch<SetStateAction<string>>; }>({
  theme: window == undefined ? "Dark" : localStorage.getItem("theme") == "Light" ? "Light" : "Dark",
  setTheme: () => {}
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [ theme, setTheme ] = useState("Dark");
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeContext.Provider value={{ theme, setTheme }}>
          <div className='global__container'>
            <header><Navbar /></header>
            <main>{children}</main>
          </div>
        </ThemeContext.Provider>
      </body>
    </html>
  )
}
