"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import StoreProvider from './StoreProvider'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'My page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
          <StoreProvider>
            <div className='global__container'>
              <header><Navbar /></header>
              <main>{children}</main>
            </div>
          </StoreProvider>
      </body>
    </html>

  )
}
